// src/components/ShuttleCard.vue
<template>
  <div class="space-y-8">
    <section v-if="store.outboundFerries.length > 0">
      <h3 class="text-lg font-semibold text-ocean-800 mb-4 flex items-center gap-2">
        <Bus class="w-5 h-5 text-ocean-500" />
        去程接驳
      </h3>
      <template v-if="!store.selectedOutboundFerryId">
        <p class="text-sm text-sand-600">请先选择船班</p>
      </template>
      <template v-else-if="store.outboundShuttles.length === 0">
        <p class="text-sm text-sand-600">暂无接驳车信息</p>
      </template>
      <template v-else>
        <div class="relative pl-6 space-y-4">
          <div class="absolute left-2 top-2 bottom-2 w-0.5 bg-ocean-200" />
          <div
            v-for="shuttle in store.outboundShuttles"
            :key="shuttle.id"
            class="relative"
          >
            <div class="absolute left-[-18px] top-4 w-3 h-3 rounded-full border-2 border-ocean-400 bg-white z-10" />
            <div
              :class="shuttleCardClass(shuttle, store.selectedOutboundShuttleId === shuttle.id)"
              @click="selectShuttle(shuttle, 'outbound')"
            >
              <div class="flex items-center gap-2 text-ocean-700 font-semibold mb-2">
                <Bus class="w-4 h-4 text-ocean-500" />
                <Clock class="w-4 h-4 text-ocean-500" />
                {{ shuttle.time }}
              </div>
              <div class="text-sm text-gray-700 mb-2">
                {{ shuttle.departure }}
              </div>
              <div class="mb-3">
                <div class="flex items-center justify-between text-xs text-gray-500 mb-1">
                  <span>{{ shuttle.capacity - shuttle.booked }}/{{ shuttle.capacity }} 余座</span>
                </div>
                <div class="h-1.5 bg-sand-100 rounded-full overflow-hidden">
                  <div
                    class="h-full rounded-full transition-all"
                    :class="capacityBarClass(shuttle)"
                    :style="{ width: capacityPercentage(shuttle) + '%' }"
                  />
                </div>
              </div>
              <div class="flex items-center gap-2">
                <span
                  v-if="shuttle.connectsFerry && shuttle.booked < shuttle.capacity"
                  class="inline-flex items-center gap-1 bg-green-50 text-green-600 text-xs px-2 py-0.5 rounded-full"
                >
                  <CheckCircle2 class="w-3.5 h-3.5" />
                  可衔接
                </span>
                <span
                  v-else-if="!shuttle.connectsFerry"
                  class="inline-flex items-center gap-1 bg-coral-50 text-coral-600 text-xs px-2 py-0.5 rounded-full"
                >
                  <XCircle class="w-3.5 h-3.5" />
                  无法衔接
                </span>
                <span
                  v-else
                  class="inline-flex items-center gap-1 bg-sand-100 text-sand-600 text-xs px-2 py-0.5 rounded-full"
                >
                  已满
                </span>
              </div>
              <p
                v-if="!shuttle.connectsFerry && shuttle.note"
                class="text-xs text-coral-500 mt-1"
              >
                {{ shuttle.note }}
              </p>
              <div
                v-if="shuttle.ferryScheduleId === store.selectedOutboundFerryId && !shuttle.connectsFerry"
                class="mt-2 bg-coral-50 border border-coral-200 rounded-lg p-2 flex items-center gap-2"
              >
                <AlertTriangle class="w-4 h-4 text-coral-500 shrink-0" />
                <span class="text-xs text-coral-600">该接驳车无法衔接您所选的去程船班</span>
              </div>
            </div>
          </div>
        </div>
      </template>
    </section>

    <section v-if="store.returnFerries.length > 0">
      <h3 class="text-lg font-semibold text-ocean-800 mb-4 flex items-center gap-2">
        <Bus class="w-5 h-5 text-ocean-500" />
        回程接驳
      </h3>
      <template v-if="!store.selectedReturnFerryId">
        <p class="text-sm text-sand-600">请先选择船班</p>
      </template>
      <template v-else-if="store.returnShuttles.length === 0">
        <p class="text-sm text-sand-600">暂无接驳车信息</p>
      </template>
      <template v-else>
        <div class="relative pl-6 space-y-4">
          <div class="absolute left-2 top-2 bottom-2 w-0.5 bg-ocean-200" />
          <div
            v-for="shuttle in store.returnShuttles"
            :key="shuttle.id"
            class="relative"
          >
            <div class="absolute left-[-18px] top-4 w-3 h-3 rounded-full border-2 border-ocean-400 bg-white z-10" />
            <div
              :class="shuttleCardClass(shuttle, store.selectedReturnShuttleId === shuttle.id)"
              @click="selectShuttle(shuttle, 'return')"
            >
              <div class="flex items-center gap-2 text-ocean-700 font-semibold mb-2">
                <Bus class="w-4 h-4 text-ocean-500" />
                <Clock class="w-4 h-4 text-ocean-500" />
                {{ shuttle.time }}
              </div>
              <div class="text-sm text-gray-700 mb-2">
                {{ shuttle.departure }}
              </div>
              <div class="mb-3">
                <div class="flex items-center justify-between text-xs text-gray-500 mb-1">
                  <span>{{ shuttle.capacity - shuttle.booked }}/{{ shuttle.capacity }} 余座</span>
                </div>
                <div class="h-1.5 bg-sand-100 rounded-full overflow-hidden">
                  <div
                    class="h-full rounded-full transition-all"
                    :class="capacityBarClass(shuttle)"
                    :style="{ width: capacityPercentage(shuttle) + '%' }"
                  />
                </div>
              </div>
              <div class="flex items-center gap-2">
                <span
                  v-if="shuttle.connectsFerry && shuttle.booked < shuttle.capacity"
                  class="inline-flex items-center gap-1 bg-green-50 text-green-600 text-xs px-2 py-0.5 rounded-full"
                >
                  <CheckCircle2 class="w-3.5 h-3.5" />
                  可衔接
                </span>
                <span
                  v-else-if="!shuttle.connectsFerry"
                  class="inline-flex items-center gap-1 bg-coral-50 text-coral-600 text-xs px-2 py-0.5 rounded-full"
                >
                  <XCircle class="w-3.5 h-3.5" />
                  无法衔接
                </span>
                <span
                  v-else
                  class="inline-flex items-center gap-1 bg-sand-100 text-sand-600 text-xs px-2 py-0.5 rounded-full"
                >
                  已满
                </span>
              </div>
              <p
                v-if="!shuttle.connectsFerry && shuttle.note"
                class="text-xs text-coral-500 mt-1"
              >
                {{ shuttle.note }}
              </p>
              <div
                v-if="shuttle.ferryScheduleId === store.selectedReturnFerryId && !shuttle.connectsFerry"
                class="mt-2 bg-coral-50 border border-coral-200 rounded-lg p-2 flex items-center gap-2"
              >
                <AlertTriangle class="w-4 h-4 text-coral-500 shrink-0" />
                <span class="text-xs text-coral-600">该接驳车无法衔接您所选的回程船班</span>
              </div>
            </div>
          </div>
        </div>
      </template>
    </section>
  </div>
</template>

<script setup lang="ts">
import { Bus, Clock, AlertTriangle, CheckCircle2, XCircle } from 'lucide-vue-next'
import { useBookingStore } from '@/composables/useBookingStore'
import type { ShuttleSchedule } from '@/utils/mockData'

const store = useBookingStore()

function capacityPercentage(shuttle: ShuttleSchedule): number {
  if (shuttle.capacity === 0) return 0
  return Math.round(((shuttle.capacity - shuttle.booked) / shuttle.capacity) * 100)
}

function capacityBarClass(shuttle: ShuttleSchedule): string {
  const remaining = shuttle.capacity - shuttle.booked
  if (remaining <= 0) return 'bg-sand-400'
  if (!shuttle.connectsFerry) return 'bg-coral-400'
  return 'bg-ocean-500'
}

function shuttleCardClass(shuttle: ShuttleSchedule, isSelected: boolean): string {
  const base = 'rounded-xl border p-4 transition-all duration-200 cursor-pointer'
  const remaining = shuttle.capacity - shuttle.booked
  if (!shuttle.connectsFerry) {
    return isSelected
      ? `${base} bg-ocean-50 border-ocean-500 shadow-md`
      : `${base} bg-white border-gray-200 hover:shadow-md`
  }
  if (remaining <= 0) {
    return `${base} bg-sand-100 border-sand-300 cursor-not-allowed hover:shadow-none`
  }
  if (isSelected) {
    return `${base} bg-ocean-50 border-ocean-500 shadow-md`
  }
  return `${base} bg-white border-gray-200 hover:shadow-md`
}

function selectShuttle(shuttle: ShuttleSchedule, direction: 'outbound' | 'return') {
  const remaining = shuttle.capacity - shuttle.booked
  if (remaining <= 0 && shuttle.connectsFerry) return
  if (direction === 'outbound') {
    store.selectedOutboundShuttleId = store.selectedOutboundShuttleId === shuttle.id ? '' : shuttle.id
  } else {
    store.selectedReturnShuttleId = store.selectedReturnShuttleId === shuttle.id ? '' : shuttle.id
  }
}
</script>

// src/components/ShuttleCard.svelte
<script lang="ts">
  import {
    outboundShuttles,
    returnShuttles,
    selectedOutboundFerryId,
    selectedReturnFerryId,
    selectedOutboundShuttleId,
    selectedReturnShuttleId,
    outboundFerries,
    returnFerries,
  } from '$lib/bookingStore'
  import { Bus, Clock, AlertTriangle, CheckCircle2, XCircle } from 'lucide-svelte'
  import type { ShuttleSchedule } from '$lib/mockData'

  function getConnectionStatus(shuttle: ShuttleSchedule, selectedFerryId: string): 'connected' | 'disconnected' | 'full' {
    if (shuttle.booked >= shuttle.capacity) return 'full'
    if (shuttle.ferryScheduleId === selectedFerryId && shuttle.connectsFerry) return 'connected'
    return 'disconnected'
  }

  function selectOutboundShuttle(id: string) {
    $selectedOutboundShuttleId = $selectedOutboundShuttleId === id ? '' : id
  }

  function selectReturnShuttle(id: string) {
    $selectedReturnShuttleId = $selectedReturnShuttleId === id ? '' : id
  }

  function hasFerryConnectionWarning(shuttle: ShuttleSchedule, selectedFerryId: string): boolean {
    if (!selectedFerryId) return false
    if (shuttle.booked >= shuttle.capacity) return false
    return shuttle.ferryScheduleId !== selectedFerryId || !shuttle.connectsFerry
  }
</script>

<div class="space-y-6">
  <div>
    <div class="flex items-center gap-2 mb-3">
      <Bus size={18} class="text-ocean-500" />
      <h3 class="font-semibold text-gray-800">去程接驳</h3>
    </div>

    {#if !$selectedOutboundFerryId}
      <div class="text-sm text-gray-400 bg-gray-50 rounded-xl p-4 text-center">
        请先选择船班
      </div>
    {:else if $outboundShuttles.length === 0}
      <div class="text-sm text-gray-400 bg-gray-50 rounded-xl p-4 text-center">
        暂无接驳车
      </div>
    {:else}
      <div class="space-y-3">
        {#each $outboundShuttles as shuttle (shuttle.id)}
          {@const status = getConnectionStatus(shuttle, $selectedOutboundFerryId)}
          {@const isSelected = $selectedOutboundShuttleId === shuttle.id}
          {@const hasWarning = hasFerryConnectionWarning(shuttle, $selectedOutboundFerryId)}

          <div
            class="bg-white rounded-xl p-4 border-2 transition-colors cursor-pointer {isSelected
              ? 'border-ocean-500'
              : 'border-transparent hover:border-ocean-200'}"
            onclick={() => selectOutboundShuttle(shuttle.id)}
            role="button"
            tabindex={0}
          >
            <div class="flex items-center justify-between mb-2">
              <div class="flex items-center gap-2">
                <Clock size={14} class="text-gray-400" />
                <span class="font-medium text-gray-800">{shuttle.time}</span>
                <span class="text-sm text-gray-400">{shuttle.departure}</span>
              </div>

              {#if status === 'connected'}
                <span class="flex items-center gap-1 text-xs font-medium text-green-600 bg-green-50 px-2 py-1 rounded-full">
                  <CheckCircle2 size={12} />
                  可衔接
                </span>
              {:else if status === 'full'}
                <span class="flex items-center gap-1 text-xs font-medium text-sand-600 bg-sand-100 px-2 py-1 rounded-full">
                  已满
                </span>
              {:else}
                <span class="flex items-center gap-1 text-xs font-medium text-coral-500 bg-coral-50 px-2 py-1 rounded-full">
                  <XCircle size={12} />
                  无法衔接
                </span>
              {/if}
            </div>

            <div class="flex items-center gap-2">
              <div class="flex-1 h-2 bg-gray-100 rounded-full overflow-hidden">
                <div
                  class="h-full rounded-full transition-all {status === 'full'
                    ? 'bg-sand-400'
                    : status === 'connected'
                      ? 'bg-green-400'
                      : 'bg-coral-300'}"
                  style="width: {(shuttle.booked / shuttle.capacity) * 100}%"
                ></div>
              </div>
              <span class="text-xs text-gray-400 shrink-0">{shuttle.booked}/{shuttle.capacity}</span>
            </div>

            {#if hasWarning && isSelected}
              <div class="flex items-start gap-2 mt-2 bg-coral-50 border border-coral-100 rounded-lg p-2">
                <AlertTriangle size={14} class="text-coral-500 mt-0.5 shrink-0" />
                <span class="text-xs text-coral-600">
                  该接驳车无法衔接所选船班{shuttle.note ? '：' + shuttle.note : ''}
                </span>
              </div>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  </div>

  <div>
    <div class="flex items-center gap-2 mb-3">
      <Bus size={18} class="text-coral-500" />
      <h3 class="font-semibold text-gray-800">回程接驳</h3>
    </div>

    {#if !$selectedReturnFerryId}
      <div class="text-sm text-gray-400 bg-gray-50 rounded-xl p-4 text-center">
        请先选择船班
      </div>
    {:else if $returnShuttles.length === 0}
      <div class="text-sm text-gray-400 bg-gray-50 rounded-xl p-4 text-center">
        暂无接驳车
      </div>
    {:else}
      <div class="space-y-3">
        {#each $returnShuttles as shuttle (shuttle.id)}
          {@const status = getConnectionStatus(shuttle, $selectedReturnFerryId)}
          {@const isSelected = $selectedReturnShuttleId === shuttle.id}
          {@const hasWarning = hasFerryConnectionWarning(shuttle, $selectedReturnFerryId)}

          <div
            class="bg-white rounded-xl p-4 border-2 transition-colors cursor-pointer {isSelected
              ? 'border-ocean-500'
              : 'border-transparent hover:border-ocean-200'}"
            onclick={() => selectReturnShuttle(shuttle.id)}
            role="button"
            tabindex={0}
          >
            <div class="flex items-center justify-between mb-2">
              <div class="flex items-center gap-2">
                <Clock size={14} class="text-gray-400" />
                <span class="font-medium text-gray-800">{shuttle.time}</span>
                <span class="text-sm text-gray-400">{shuttle.departure}</span>
              </div>

              {#if status === 'connected'}
                <span class="flex items-center gap-1 text-xs font-medium text-green-600 bg-green-50 px-2 py-1 rounded-full">
                  <CheckCircle2 size={12} />
                  可衔接
                </span>
              {:else if status === 'full'}
                <span class="flex items-center gap-1 text-xs font-medium text-sand-600 bg-sand-100 px-2 py-1 rounded-full">
                  已满
                </span>
              {:else}
                <span class="flex items-center gap-1 text-xs font-medium text-coral-500 bg-coral-50 px-2 py-1 rounded-full">
                  <XCircle size={12} />
                  无法衔接
                </span>
              {/if}
            </div>

            <div class="flex items-center gap-2">
              <div class="flex-1 h-2 bg-gray-100 rounded-full overflow-hidden">
                <div
                  class="h-full rounded-full transition-all {status === 'full'
                    ? 'bg-sand-400'
                    : status === 'connected'
                      ? 'bg-green-400'
                      : 'bg-coral-300'}"
                  style="width: {(shuttle.booked / shuttle.capacity) * 100}%"
                ></div>
              </div>
              <span class="text-xs text-gray-400 shrink-0">{shuttle.booked}/{shuttle.capacity}</span>
            </div>

            {#if hasWarning && isSelected}
              <div class="flex items-start gap-2 mt-2 bg-coral-50 border border-coral-100 rounded-lg p-2">
                <AlertTriangle size={14} class="text-coral-500 mt-0.5 shrink-0" />
                <span class="text-xs text-coral-600">
                  该接驳车无法衔接所选船班{shuttle.note ? '：' + shuttle.note : ''}
                </span>
              </div>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>
